### ISSUE TITLE
Move tachyons overrides into tachyons-egghead repo

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/tachyons-egghead#21]
Looking at a PR [like this](https://github.com/eggheadio/tachyons-egghead/pull/20), it is unclear what has been changed since the changes are tucked away in forked separate repos and composed from `node_modules`.

As I mentioned in https://paper.dropbox.com/doc/egghead-project-boundaries-NxDI1mVZz1fr0ep3ecLax, an idea to simplify all the tachyons egghead development would be to:
> "we move all our tachyons-* forked modules into files directly in the project like tachyons-egghead/src/overrides/tachyons-colors  so that a single PR can contain the code updates and the bumped library version"

That way, https://github.com/eggheadio/tachyons-egghead/pull/20 + https://github.com/eggheadio/tachyons-colors/pull/3 + https://github.com/eggheadio/tachyons-skins/pull/2 etc. (all the egghead tachyons overrides) could be done in one place with one PR; would help PRs make sense other than having `node_modules` "side effects".

This should also remove the old color values.

**Comment by trevordmiller** [comment]
An idea for implementation:
copy each `tachyons-*` egghead fork `src/*.css` file into `tachyons-egghead/src/overrides` and then changing [these imports](https://github.com/eggheadio/tachyons-egghead/blob/master/src/tachyons.css#L53-L59) to point to `./overrides/*` instead of `node_modules`.

**Comment by joelhooks** [comment]
@DrShpongle  and I were talking about this yesterday because the way the modules handle color vars is REALLY tedious.

Any idea that we would merge from upstream tachyons repo is really just a pipe dream. It would need to be done manually anyway...

**Comment by trevordmiller** [comment]
Resolved by https://github.com/eggheadio/tachyons-egghead/pull/27

**Comment by trevordmiller** [comment]
Woops wrong issue.
